### ISSUE TITLE
enforce_private does not work in REPL

### ISSUE THREAD

**Issue by MostAwesomeDude** [amitassaraf/lang#2]
```
>>> from lang.access import enforce_private
>>> @enforce_private
... class Box(object):
...  def __init__(self):
...   self._cheese_ = 42
...
>>> Box()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lang/access.py", line 273, in __init__
    cls.__init__(self, *args, **kwargs)
  File "<stdin>", line 4, in __init__
  File "lang/access.py", line 203, in <lambda>
    **kwargs))
  File "lang/access.py", line 29, in _private_member_access_protection
    code_context = inspect.getsourcelines(frame)
  File "/usr/lib/python2.7/inspect.py", line 690, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/lib/python2.7/inspect.py", line 538, in findsource
    raise IOError('could not get source code')
IOError: could not get source code
```

**Comment by amitassaraf** [comment]
@MostAwesomeDude Thanks for everything, Would you like to join the repo and maintain it with me? Tell me and ill give you permissions :)

**Comment by MostAwesomeDude** [comment]
No, I'm working on the Monte programming language, which builds this sort of stuff directly into the semantics. I just thought that you might like to know about some of the inevitable pitfalls that await you.
