### ISSUE TITLE
Installing using pip install doesn't work

### ISSUE THREAD

**Issue by sundarnagarajan** [amitassaraf/lang#5]
Good work - I really liked this. When trying to install using 'pip install lang' in Python 2.7, I get the following error:

Downloading/unpacking lang
  Downloading lang-1.0.5.tar.gz
  Running setup.py (path:/mnt/auto/content/virtualenv/try/build/lang/setup.py) egg_info for package lang
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/mnt/auto/content/virtualenv/try/build/lang/setup.py", line 14, in <module>
        with open(path.join(here, '..', 'README.md'), encoding='utf-8') as f:
      File "/mnt/auto/content/virtualenv/try/lib/python2.7/codecs.py", line 878, in open
        file = **builtin**.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: '/mnt/auto/content/virtualenv/try/build/lang/../README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/mnt/auto/content/virtualenv/try/build/lang/setup.py", line 14, in <module>
    with open(path.join(here, '..', 'README.md'), encoding='utf-8') as f:
  File "/mnt/auto/content/virtualenv/try/lib/python2.7/codecs.py", line 878, in open
    file = **builtin**.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: '/mnt/auto/content/virtualenv/try/build/lang/../README.md'

Installing using 'python setup.py install' works, and the package is great.

As another issue has mentioned, it doesn't work as expected using REPL.

**Comment by darkopevec** [comment]
Hi,
I believe this issue is still open, my pip install lang breaks with the same error:

IOError: [Errno 2] No such file or directory: '/tmp/pip-install-4C0hiS/lang/../README.md'
